In [3]:
import pandas as pd

path_df = pd.read_csv('trajectory.csv', header=0, names=['t', 'x', 'y', 'theta', 'v', 'w'])

In [4]:
path_df

             t         x         y     theta         v         w
0     0.533333  0.114023 -0.032303 -0.339719  0.445058 -0.853967
1     1.066667  0.311131 -0.160128 -0.687618  0.500000 -0.537629
2     1.600000  0.481240 -0.342670 -0.887065  0.500000 -0.260159
3     2.133333  0.629074 -0.544188 -0.963269  0.500000 -0.044655
4     2.666667  0.775522 -0.746793 -0.935742  0.500000  0.154762
..         ...       ...       ...       ...       ...       ...
186  93.866667 -0.010000  0.010000  3.310869  0.000000 -0.101556
187  94.400000 -0.010000  0.010000  3.269374  0.000000 -0.064424
188  94.933333 -0.010000  0.010000  3.244367  0.000000 -0.035603
189  95.466667 -0.010000  0.010000  3.232621  0.000000 -0.011380
190  96.000000 -0.010000  0.010000  3.131593  0.000000 -0.392734

[191 rows x 6 columns]

In [ ]:
%matplotlib inline

from matplotlib import pyplot as plt